version: "3"
services:
  web:
    container_name: nginx
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./web/:/var/www/ 
      - ./nginx.php-fpm.conf:/etc/nginx/nginx.conf:ro
    links:
      - php-fpm

  # Configuración de php
  php-fpm:
    container_name: php
    build: .
    volumes:
      - ./web:/var/www/html

  nodeapi:
    image: "node:latest"
    container_name: "nodejs"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes: 
      - ./api:/home/node/app
    ports:
      - "3000:3000"
    command: "npm run start" 

  #MongoDB
  mongo:
    container_name: mongodb
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    ports:
      - "27017:27017"



  
