version: "3"
services:
  nodeapi:
    image: "node:latest"
    container_name: "nodejs"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes: 
      - ./:/home/node/app
    ports:
      - "3000:3000"
    command: "npm run dev" 


  